# EMWM Linux Makefile

PREFIX = /usr
MANDIR = $(PREFIX)/share/man
RCDIR = /usr/lib/X11
APPLRESDIR = /usr/lib/X11/app-defaults

INCDIRS = -I/usr/local/include 
LIBDIRS = -L/usr/local/lib

CFLAGS = -O2 -Wall $(INCDIRS)

include common.mf

install: common_install

-include .depend
